---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Default
    name: Default
    inherits: 
    description: 
  fields:
  - approval_type:
      value: multi-level
  - max_vms:
      value: '1'
